name = "album-digital-bodas"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run build"

[vars]
# Las variables de entorno también se pueden poner aquí, 
# pero es mejor dejarlas en el panel de Cloudflare por seguridad.
